title: 'ACADIA'
description: "2025 ACADIA CONFERENCE"
baseurl: ""
url: "https://2025.acadia.org"
logo: "/assets/images/acadia_logo.png"
2025logo: "/assets/images/logo-l.png"

header_pages:
  # - index.md
  - workshops.md
  - registration.md
  - schedule.md
  - calls.md
  - awards.md
  - sponsors.md
  - miami.md
  - hosts.md
  - gallery.md

style: light

footer: 'follow us on <a href="https://www.instagram.com/acadiaorg/">Instagram</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
plugins:
  - jekyll-seo-tag
