title: 'ACADIA'
description: "2025 ACADIA CONFERENCE"
baseurl: ""
url: "https://2025.acadia.org"
logo: "/assets/images/acadia_logo.png"
2025logo: "/assets/images/logo-l.png"

header_pages:
  # - index.md
  - title: Attend
    children:
      - registration.md
      - schedule.md
      - miami.md
  - title: Submit
    children:
      - calls.md
  - title: Program
    children:
      - workshops.md
      - awards.md
      - gallery.md
  - title: About
    children:
      - hosts.md
      - sponsors.md

style: light

footer: 'follow us on <a href="https://www.instagram.com/acadiaorg/">Instagram</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
plugins:
  - jekyll-seo-tag
